import org.apache.commons.lang3.StringUtils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(StringUtils.abbreviate(new App().getGreeting(), 4));
    }
}
